### ISSUE TITLE
class内ではgetメソッドの代わりにgetterを使う

### ISSUE THREAD

**Issue by koyashiro** [sansuke05/es6-examples#1]
ES5から`get`構文が追加されているため、class内では`getFoo()`といったメソッドよりもこちらを使ったほうが良いかと思います。

## 参考

- [ゲッター \- JavaScript \| MDN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Functions/get)
- [セッター \- JavaScript \| MDN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Functions/set)
- [オブジェクトでの作業 \- JavaScript \| MDN #ゲッターとセッターの定義](https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Working_with_Objects#Defining_getters_and_setters)

**Comment by sansuke05** [comment]
修正PRマージしました！
https://github.com/sansuke05/es6-examples/pull/2
